spring:
  application:
    name: judge
  rabbitmq:
#    host: message-broker
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
server:
  port: 8090
